# Generated by Django 6.0.3 on 2026-03-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('languages', 'Languages'), ('frameworks', 'Frameworks'), ('ml', 'Machine Learning'), ('tools', 'Tools'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
